name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.17.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set env
        id: set_env
        run: echo ::set-output name=RELEASE_VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Get dependencies
        run: go mod download

      - name: Release to Github
        run: |
          ./scripts/git_release.sh github_api_token=${{ secrets.RELEASE_TOKEN }} owner=PxyUp repo=binance_bot tag=${{ steps.set_env.outputs.RELEASE_VERSION }} filename=./bin/${{ steps.set_env.outputs.RELEASE_VERSION }}-binance_bot-linux-arm64
          ./scripts/git_release.sh github_api_token=${{ secrets.RELEASE_TOKEN }} owner=PxyUp repo=binance_bot tag=${{ steps.set_env.outputs.RELEASE_VERSION }} filename=./bin/${{ steps.set_env.outputs.RELEASE_VERSION }}-binance_bot-windows-amd64.exe
          ./scripts/git_release.sh github_api_token=${{ secrets.RELEASE_TOKEN }} owner=PxyUp repo=binance_bot tag=${{ steps.set_env.outputs.RELEASE_VERSION }} filename=./bin/${{ steps.set_env.outputs.RELEASE_VERSION }}-binance_bot-linux-amd64
  build_mac_agent:
    name: Build mac agent with cgo
    runs-on: macOS-10.15
    needs: build
    steps:
      - name: Set up Go 1.15.7
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set env
        id: set_env
        run: echo ::set-output name=RELEASE_VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Get dependencies
        run: go mod download

      - name: Release Github Mac
        run: |
          make build_mac version=${{ steps.set_env.outputs.RELEASE_VERSION }}
          ./scripts/git_release.sh github_api_token=${{ secrets.RELEASE_TOKEN }} owner=PxyUp repo=binance_bot tag=${{ steps.set_env.outputs.RELEASE_VERSION }} filename=./bin/${{ steps.set_env.outputs.RELEASE_VERSION }}-binance_bot-darwin-amd64